### ISSUE TITLE
crashing after b1.5.1

### ISSUE THREAD

**Issue by larryngton** [xia-mc/Raven-bS#10]
probably caused by the killaura rot system recode
[crash-2024-06-23_12.43.02-client.txt](https://github.com/user-attachments/files/15944037/crash-2024-06-23_12.43.02-client.txt)

**Comment by xia-mc** [comment]
According to stacktrace, this could be caused by the CPS calculator system... This code was last modified 18 days ago. To further diagnose the problem, can you use this mod below? If the game continues to crash or an error pops up in the bottom left corner, please send me a log and screenshot, thanks.
![image](https://github.com/xia-mc/Raven-bS/assets/108219418/650df102-f0d1-4372-a947-f17d1b5df981)

Mod: [raven-bS.zip](https://github.com/user-attachments/files/15944639/raven-bS.zip)

**Comment by larryngton** [comment]
> According to stacktrace, this could be caused by the CPS calculator system... This code was last modified 18 days ago. To further diagnose the problem, can you use this mod below? If the game continues to crash or an error pops up in the bottom left corner, please send me a log and screenshot, thanks. ![image](https://private-user-images.githubusercontent.com/108219418/342065778-650df102-f0d1-4372-a947-f17d1b5df981.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxNzM3NjUsIm5iZiI6MTcxOTE3MzQ2NSwicGF0aCI6Ii8xMDgyMTk0MTgvMzQyMDY1Nzc4LTY1MGRmMTAyLWYwZDEtNDM3Mi1hOTQ3LWYxN2QxYjVkZjk4MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyM1QyMDExMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMzExYWVkYmJlNTlmMzMyYzI0OGNmMjJjNGIzN2QzMDlkNDk0ZDcxY2YyYzdjM2NiZWU0ZjM2Y2MwODNkMWM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Jmx2iSCIioHk5jepvMCLbX_EJi9IdsfuGu854HKf7Lw)
> 
> Mod: [raven-bS.zip](https://github.com/user-attachments/files/15944639/raven-bS.zip)

works as expected now, thanks
